version = 1

test_patterns = ["/tests/**/test_*.py"]

exclude_patterns = [
    "/example_config/**",
    "/docs/**",
    "/default_plugins/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
