version: '3'
# Never use this in a production environment.
# Run with docker-compose -f docker-compose-saml.yaml up
services:
  consoleme:
    build: .
    ports:
      - "8081:8081"
    tty: true
    stdin_open: true
    volumes:
      - .:/apps/consoleme
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
    environment:
      - CONFIG_LOCATION=/apps/consoleme/docker/example_config_credential_auth.yaml
    # Run commands to install Consoleme, run the service, and never exit in the event of failure (For dev debugging)
    command: >
      bash -c 'pip install argh watchdog; pip install -e /apps/consoleme/default_plugins;
      watchmedo auto-restart --recursive --pattern="*.py;*.yaml" --directory="." python consoleme/__main__.py'
    depends_on:
      - consoleme_redis
      - consoleme_dynamodb
      - consoleme_oidc
    links:
      - consoleme_redis
      - consoleme_dynamodb
      - consoleme_oidc

  consoleme_oidc:
    image: "qlik/simple-oidc-provider"
    volumes:
      - ./docker/simple-oidc-provider:/simple-oidc-provider-settings
    container_name: consoleme_oidc
    ports:
      - "9000:9000"
    environment:
      - CONFIG_FILE=/simple-oidc-provider-settings/idp_config.json
      - USERS_FILE=/simple-oidc-provider-settings/idp_users.json
      - DEBUG=oidc-provider:*
