version: '3'
# Never use this in a production environment.
# Run with docker-compose -f docker-compose-saml.yaml up
services:
  consoleme:
    build: .
    ports:
      - "8081:8081"
    tty: true
    stdin_open: true
    volumes:
      - .:/apps/consoleme:delegated
      - ~/.aws:/root/.aws:cached
      - ~/.ssh:/root/.ssh:cached
    environment:
      - CONFIG_LOCATION=/apps/consoleme/docker/example_config_saml.yaml
    # Run commands to install Consoleme, run the service, and never exit in the event of failure (For dev debugging)
    command: >
      bash -c 'pip install argh watchdog; pip install -e /apps/consoleme/default_plugins;
      watchmedo auto-restart --recursive --pattern="*.py;*.yaml" --directory="." python consoleme/__main__.py'
    depends_on:
      - consoleme_redis
      - consoleme_dynamodb
      - consoleme_saml
    links:
      - consoleme_redis
      - consoleme_dynamodb
      - consoleme_saml

  consoleme_saml:
    image: "kristophjunge/test-saml-idp"
    volumes:
      - ./docker/simplesamlphp/authsources.php:/var/www/simplesamlphp/config/authsources.php:delegated
    container_name: consoleme_simplesaml
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://localhost:8081
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:8081/saml/acs
