openapi: 3.0.0
info:
  description: ConsoleMe API definition
  version: '2.0.0'
  title: ConsoleMe v2 API
  contact:
    email: psanders@netflix.com
  license:
    name: License TBD
tags:
  - name: default
    description: Cool stuff
paths:
  /credentials:
    post:
      summary: generate a federation url for aws console signin
  /policies:
    get:
      summary: get a list of policies
  /requests:
    get:
      summary: get a list of requests
    post:
      summary: submit a new request
  /requests/{id}:
    get:
      summary: get details about a request
    put:
      summary: update a request
  /roles/{accountNumber}/{roleName}:
    get:
      summary: get details about a role
    put:
      summary: update a role
  /roles/{accountNumber}/{roleName}/requests:
    get:
      summary: get a list of requests for a role
  /roles/{accountNumber}/{roleName}/requests/{id}:
    get:
      summary: get details about a request for a role
