extends:
  - example_config_base.yaml
  - example_secrets.yaml

auth:
  get_groups_by_header: false
  get_user_by_header: false
  get_user_by_oauth: false
  get_user_by_oidc: true
  get_user_by_saml: false
  groups_header_name: group_header
  user_header_name: user_header
  set_auth_cookie: true


get_user_by_oidc_settings:
  resource: consoleme-oidc
  authorize_url: http://localhost:8080/auth/realms/consoleme/protocol/openid-connect/auth
  issuer: http://localhost:8080/auth/realms/consoleme
  token_endpoint: http://localhost:8080/auth/realms/consoleme/protocol/openid-connect/token
  token_introspection_endpoint: http://localhost:8080/auth/realms/consoleme/protocol/openid-connect/token/introspect
  userinfo_endpoint: http://localhost:8080/auth/realms/consoleme/protocol/openid-connect/userinfo
  jwt_verify: false
  jwt_email_key: email
  jwt_groups_key: groups

development: true

url: http://127.0.0.1:8081

tornado:
  debug: true
  port: 8081
  xsrf: false

google:
  service_key_file: docker/test_google_secret.json

duo:
  lambda_arn: arn:aws:lambda:{}:123456789012:function:duo_lambda

challenge:
  expiration: 600

celery_jobs:
  cloudtrail_errors:
    sleep_time: 0

logging:
  format: '%(asctime)s - %(levelname)s - %(name)s - [%(filename)s:%(lineno)s - %(funcName)s() ] - %(message)s'
  stdout_enabled: true
  level: debug
  elasticsearch:
    level: DEBUG
  file: ~/.consoleme/consoleme_tornado.log

aws:
  account_number: 123456789012
  region: us-east-1

ses:
  consoleme:
    sender: consoleme_test@fakedomain.com
    name: Consoleme
  accessui:
    sender: access_ui_test@fakedomain.com
    name: Access UI
