account_ids_to_name:
  123456789012: default_account
  123456789013: prod
  123456789014: test

# A development configuration can specify a specific user to impersonate locally.
_development_user_override: consoleme_admin@example.com

# A development configuration can override your groups locally
_development_groups_override:
  - groupa@example.com
  - groupb@example.com
  - configeditors@example.com
  - consoleme_admins@example.com

logging:
  stdout_enabled: true
  format: '%(asctime)s - %(levelname)s - %(name)s - [%(filename)s:%(lineno)s - %(funcName)s() ] - %(message)s'
  level: debug
  file: /logs/consoleme/consoleme_tornado.log