apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consoleme.fullname" . }}-config-redis
  labels:
    {{- include "consoleme.labels" . | nindent 4 }}
data:
  config_redis.yaml: |
    celery:
      broker_url: {{ .Values.redis.broker_url }}
      broker:
        {{ .Values.redis.region }}: {{ .Values.redis.broker_url }}
      backend:
        {{ .Values.redis.region }}: {{ .Values.redis.broker_url }}
      debug: false

      {{- if .Values.event_bridge.enabled }}
      trigger_credential_mapping_refresh_from_role_changes:
        enabled: true
      cache_cloudtrail_denies:
        enabled: true
      {{- end }}

      {{- if .Values.redis.sync_regions }}
      sync_regions:
        {{- toYaml .Values.redis.sync_regions | nindent 8 }}
      {{- end }}

    redis:
      host:
        {{ .Values.redis.region }}: {{ .Values.redis.host }}
      db: {{ .Values.redis.db }}
      port: {{ .Values.redis.port }}
