apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consoleme.fullname" . }}-config-redis
  labels:
    {{- include "consoleme.labels" . | nindent 4 }}
data:
  config_redis.yaml: |
    celery:
      broker_url: {{ .Values.redis.broker_url }}
      broker:
        {{ .Values.redis.region }}: {{ .Values.redis.broker_url }}
      backend:
        {{ .Values.redis.region }}: {{ .Values.redis.broker_url }}
      debug: false

    redis:
      host:
        {{ .Values.redis.region }}: {{ .Values.redis.host }}
      db: {{ .Values.redis.db }}
      port: {{ .Values.redis.port }}
