apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consoleme.fullname" . }}-config-dynamo
  labels:
    {{- include "consoleme.labels" . | nindent 4 }}
data:
  config_dynamo.yaml: |
    dynamodb_server: {{ .Values.dynamodb.url }}
