apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consoleme.fullname" . }}-config
  labels:
    {{- include "consoleme.labels" . | nindent 4 }}
data:
  config.yaml: |
    extends:
      - config_base.yaml
      - config_dynamo.yaml
      - config_redis.yaml
      - config_auth.yaml
    {{- if .Values.cache_accounts_from_aws_organizations.enabled }}
      - config_organization.yaml
    {{- end }}
    {{- if .Values.awsSecretsManager.enabled }}
      - AWS_SECRETS_MANAGER:{{ .Values.awsSecretsManager.name }}
    {{- else }}
      - secrets/secrets.yaml
    {{- end }}
