apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consoleme.fullname" . }}-celery
  labels:
    {{- include "consoleme.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consoleme.celery.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "consoleme.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap-base: {{ include (print $.Template.BasePath "/configmap-base.yaml") . | sha256sum }}
        checksum/configmap-dynamo: {{ include (print $.Template.BasePath "/configmap-dynamo.yaml") . | sha256sum }}
        checksum/configmap-redis: {{ include (print $.Template.BasePath "/configmap-redis.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if (eq "saml" .Values.authentication.type) }}
        checksum/secrets-certs: {{ include (print $.Template.BasePath "/secrets-certs.yaml") . | sha256sum }}
        checksum/configmap-auth-saml: {{ include (print $.Template.BasePath "/configmap-auth-saml.yaml") . | sha256sum }}
        {{- else if (eq "header" .Values.authentication.type) }}
        checksum/configmap-auth-header: {{ include (print $.Template.BasePath "/configmap-auth-header.yaml") . | sha256sum }}
        {{- else if (eq "oidc" .Values.authentication.type) }}
        checksum/configmap-auth-oidc: {{ include (print $.Template.BasePath "/configmap-auth-oidc.yaml") . | sha256sum }}
        {{- else if (eq "alb" .Values.authentication.type) }}
        checksum/configmap-auth-alb: {{ include (print $.Template.BasePath "/configmap-auth-alb.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "consoleme.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "consoleme.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-celery
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest}}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash","-c", {{ .Values.consoleme.celery.command }}]
          resources:
            {{- toYaml .Values.consoleme.celery.resources | nindent 12 }}
          env: {{- toYaml .Values.consoleme.celery.env | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/consoleme/secrets
              name: consoleme-secrets
            - mountPath: /etc/consoleme/config.yaml
              name: consoleme-config
              readOnly: true
              subPath: config.yaml
            - mountPath: /etc/consoleme/config_base.yaml
              name: consoleme-config-base
              readOnly: true
              subPath: config_base.yaml
            - mountPath: /etc/consoleme/config_auth.yaml
              name: consoleme-config-auth
              readOnly: true
              subPath: config_auth.yaml
            {{- if .Values.cache_accounts_from_aws_organizations.enabled }}
            - mountPath: /etc/consoleme/config_organization.yaml
              name: consoleme-config-organization
              subPath: config_organization.yaml
              readOnly: true
            {{- end }}
            - mountPath: /etc/consoleme/config_redis.yaml
              name: consoleme-config-redis
              readOnly: true
              subPath: config_redis.yaml
            - mountPath: /etc/consoleme/config_dynamo.yaml
              name: consoleme-config-dynamo
              readOnly: true
              subPath: config_dynamo.yaml
      volumes:
        - name: consoleme-secrets
          secret:
            secretName: {{ include "consoleme.fullname" . }}-secrets
        - name: consoleme-config
          configMap:
            name: {{ include "consoleme.fullname" . }}-config
        - name: consoleme-config-base
          configMap:
            name: {{ include "consoleme.fullname" . }}-config-base
        - name: consoleme-config-auth
          configMap:
            name: {{ include "consoleme.fullname" . }}-config-auth
        {{- if .Values.cache_accounts_from_aws_organizations.enabled }}
        - name: consoleme-config-organization
          configMap:
            name: {{ include "consoleme.fullname" . }}-config-organization
        {{- end }}
        - name: consoleme-config-redis
          configMap:
            name: {{ include "consoleme.fullname" . }}-config-redis
        - name: consoleme-config-dynamo
          configMap:
            name: {{ include "consoleme.fullname" . }}-config-dynamo
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
