{{- if .Values.ingress.enabled -}}
{{- $fullName := include "consoleme.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "consoleme.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules: {{- toYaml .Values.ingress.hosts | nindent  4}}
  {{- end }}
