apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consoleme.fullname" . }}-secrets
  labels:
    {{- include "consoleme.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.yaml: |-
    sentry:
      dsn: {{ .Values.sentry.dsn }}

    {{- if .Values.consoleme.jwt_secret }}
    jwt_secret: {{ .Values.consoleme.jwt_secret  }}
    {{- end }}

    {{- if (eq "oidc" .Values.authentication.type) }}
    {{- with .Values.authentication.oidc_config.oidc_secrets }}
    oidc_secrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
