{{- if (eq "saml" .Values.authentication.type) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consoleme.fullname" . }}-certs
  labels:
    {{- include "consoleme.labels" . | nindent 4 }}
type: Opaque
stringData:
  sp.crt: |- {{ .Values.authentication.saml_config.sp_cert | nindent 4 }}
  sp.key: |- {{ .Values.authentication.saml_config.sp_key | nindent 4 }}
{{- end }}
