# Warning: The following configuration file is an example, and it is insecure by default. Please carefully
# review and change values accordingly before deploying to a production environment. You are responsible
# for your deployment.

extends:
  - example_config_development.yaml

dynamodb_server: http://CONSOLEME-DYNAMODB:8005

celery:
  broker:
    us-east-1: redis://consoleme-redis:6379/1
    us-west-2: redis://consoleme-redis:6379/1
  backend:
    us-east-1: redis://consoleme-redis:6379/2
    us-west-2: redis://consoleme-redis:6379/2
  debug: true

redis:
  host:
    us-east-1: consoleme-redis
    us-west-2: consoleme-redis
  db: 0
  port: 6379
# You may optionally use the docker-compose-zipkin.yaml file to run Zipkin. You can enable distributed tracing
# with the following configuration:
# tracing:
#   zipkin_address: http://consoleme-zipkin:9411/api/v2/spans
