# Warning: The following configuration file is an example, and it is insecure by default. Please carefully
# review and change values accordingly before deploying to a production environment. You are responsible
# for your deployment.

# You'll need to tell ConsoleMe which configuration to use. You can do this by setting the CONFIG_LOCATION environment
# variable to the full path of your configuration.
# Example:
# CONFIG_LOCATION=/home/username/.config/consoleme/development.yaml

# You can "extend" configurations with other configurations. This will basically merge the two configurations. The
# primary configuration file is the one that you've defined in your CONFIG_LOCATION environment variable. This is useful
# when you have common configuration values across all of your deployments, but also some configuration values that are
# specific to your deployment.
extends:
  - example_config_base.yaml
  - example_secrets.yaml

auth:
  # These configuration settings tell ConsoleMe to look at plaintext header values to determine the user's identity and
  # their groups. You'll need to change user_header_name/groups_header_name to the appropriate header names for your
  # environment. To avoid client side header forgery, you should ensure ConsoleMe is fronted by Apache/Nginx. Your
  # web server should drop sensitive headers so that users cannot forge them, authenticate the users, and pass down the
  # plaintext headers for ConsoleMe to consume.
  # The user header is your user identifier. Usually a username or an e-mail address.
  # The groups header provides a comma separated list of groups that the user is a member of. Group headers cna be plain
  # strings, or if you use something like Google groups, they can also be e-mail addresses.

  # Example headers:
  # user_header: curtis@example.com
  # groups_header: group1,group2,group3
  get_groups_by_header: true
  get_user_by_header: true
  groups_header_name: group_header
  user_header_name: user_header

# Development mode provides functionality to ease local development. You should only use this mode locally.
development: true

# This defines the URL that ConsoleMe is hosted at. Be sure to change this in your production environment.
url: http://localhost:8081
