extends:
  - example_config_development.yaml

dynamodb_server: http://CONSOLEME-DYNAMODB:8005

celery:
  broker_url: redis://consoleme-redis:6379/1
  broker:
    us-east-1: redis://consoleme-redis:6379/1
    us-west-2: redis://consoleme-redis:6379/1
  backend:
    us-east-1: redis://consoleme-redis:6379/1
    us-west-2: redis://consoleme-redis:6379/1
  debug: true

redis:
  host:
    us-east-1: consoleme-redis
    us-west-2: consoleme-redis
  db: 0
  port: 6379
# You may optionally use the docker-compose-zipkin.yaml file to run Zipkin. You can enable distributed tracing
# with the following configuration:
# tracing:
#   zipkin_address: http://consoleme-zipkin:9411/api/v2/spans
